Repository MaximeZmt/SDP_2022-Vibester, pull requests merged in 2022-04, with the labels that each got.

#179 Kamila/typing game disable guess
  app/src/androidTest/java/ch/sdp/vibester/model/UserSharedPrefTest.kt
  app/src/main/java/ch/sdp/vibester/activity/TypingGameActivity.kt
Labels: enhancement

#180 Rework Authentication
  app/src/androidTest/java/ch/sdp/vibester/activity/AuthenticationActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/WelcomeActivityTest.kt
  app/src/main/java/ch/sdp/vibester/activity/AuthenticationActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/ProfileActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/WelcomeActivity.kt
  app/src/main/java/ch/sdp/vibester/auth/FireBaseAuthenticator.kt
  app/src/main/java/ch/sdp/vibester/database/UsersRepo.kt
  app/src/main/res/layout/activity_authentication.xml
  app/src/main/res/layout/activity_google_log_in.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_welcome_screen.xml
  app/src/main/res/values/strings.xml
Labels: actual: 10h

#190 Refactor Auth + Going forward score part 2
  app/src/androidTest/java/ch/sdp/vibester/UtilTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/AuthenticationActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/BuzzerScreenActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/BuzzerSetupActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/CreateProfileActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/DownloadActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/GameEndingActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/GameSetupActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/LyricsBelongGameActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/ProfileActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/ScoreBoardActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/TypingGameActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/activity/WelcomeActivityTest.kt
  app/src/androidTest/java/ch/sdp/vibester/auth/FireBaseAuthenticatorTest.kt
  app/src/androidTest/java/ch/sdp/vibester/model/UserSharedPrefTest.kt
  app/src/main/java/ch/sdp/vibester/TestMode.kt
  app/src/main/java/ch/sdp/vibester/activity/AuthenticationActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/BuzzerScreenActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/BuzzerSetupActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/CreateProfileActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/DownloadActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/GameActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/GameEndingActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/GameSetupActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/LyricsBelongGameActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/ProfileActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/SearchUserActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/TypingGameActivity.kt
  app/src/main/java/ch/sdp/vibester/activity/WelcomeActivity.kt
  app/src/main/java/ch/sdp/vibester/api/InternetState.kt
  app/src/main/java/ch/sdp/vibester/auth/FireBaseAuthenticator.kt
  app/src/main/java/ch/sdp/vibester/database/DataGetter.kt
  app/src/main/java/ch/sdp/vibester/database/Database.kt
  app/src/main/java/ch/sdp/vibester/database/PersistanceSetter.kt
  app/src/main/java/ch/sdp/vibester/model/UserSharedPref.kt
  app/src/main/java/ch/sdp/vibester/user/UserProfileAdapter.kt
  app/src/main/java/ch/sdp/vibester/util/Util.kt
  app/src/main/res/layout/activity_authentication.xml
  app/src/main/res/layout/activity_game_setup_screen.xml
  app/src/main/res/layout/activity_welcome_screen.xml
  app/src/main/res/values/strings.xml
Labels: actual: >10h
